name: Build Hugo

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'  # Replace with your Hugo version

      - name: Build Hugo site
        run: hugo --minify